services:

  - type: web
    name: safebhoomi
    runtime: python
    buildCommand: pip install -r backend/requirements.txt && cd frontend_react && npm install && npm run build
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
